name: Testsuite

on: [push]

jobs:

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 6
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.14']

    steps:
    - name: Checkout repository (with libsodium submodule)
      uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install package
      run: |
        pip install . --no-cache-dir

    - name: Install newer bash for macOS
      if: matrix.os == 'macos-latest'
      run: |
        brew install bash

    - name: Install Bats
      run: |
        git clone https://github.com/bats-core/bats-core.git
        pushd bats-core && git checkout v1.1.0 && sudo ./install.sh /usr/local && popd

    - name: Run bats tests
      run: |
        bats tests


  build-system:
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 6
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.14']

    steps:
    - name: Checkout repository (without libsodium submodule)
      uses: actions/checkout@v6

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install pkg-config and libsodium (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install pkg-config libsodium bash

    - name: Install pkg-config and libsodium (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        sudo apt-get update
        sudo apt-get install -y pkg-config libsodium-dev

    - name: Install package with system-wide libsodium
      run: |
        export SODIUM_INSTALL=system
        export CFLAGS="$(pkg-config --cflags libsodium)"
        if [ "$RUNNER_OS" = "Linux" ]; then
            export LDFLAGS="-Wl,--no-as-needed $(pkg-config --libs libsodium)"
        else
            export LDFLAGS="$(pkg-config --libs libsodium)"
        fi
        pip install . --no-cache-dir

    - name: Install Bats
      run: |
        git clone https://github.com/bats-core/bats-core.git
        pushd bats-core && git checkout v1.1.0 && sudo ./install.sh /usr/local && popd

    - name: Run bats tests
      run: |
        bats tests
