name: Testsuite

on: [push]

jobs:

  build:
    runs-on: ${{ matrix.os }}

    strategy:
      max-parallel: 6
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
        python-version: ['3.9', '3.10', '3.11', '3.12', '3.13', '3.14']
        install: ['system', 'bundled']

    steps:
    - name: Checkout repository (with libsodium submodule)
      if: matrix.install == 'bundled'
      uses: actions/checkout@v6
      with:
        submodules: recursive

    - name: Checkout repository (with system-wide libsodium)
      if: matrix.install != 'bundled'
      uses: actions/checkout@v6

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v6
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install Python dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Install Crypt4GH with system-wide libsodium (macOS)
      if: matrix.os == 'macos-latest' && matrix.install == 'system'
      run: |
        brew install pkg-config libsodium
        export SODIUM_INSTALL=system
        export CFLAGS="$(pkg-config --cflags libsodium)"
        export LDFLAGS="$(pkg-config --libs libsodium)"
        pip install . --no-cache-dir

    - name: Install Crypt4GH with system-wide libsodium (Ubuntu)
      if: matrix.os == 'ubuntu-latest' && matrix.install == 'system'
      run: |
        apt-get update
        apt-get install -y pkg-config libsodium-dev
        export SODIUM_INSTALL=system
        export LDFLAGS="-Wl,--no-as-needed $(pkg-config --libs libsodium)"
        export LDFLAGS="$(pkg-config --libs libsodium)"
        pip install . --no-cache-dir

    - name: Install package (bundled)
      if: matrix.install != 'system'
      run: |
        pip install . --no-cache-dir

    - name: Install bats (macOS)
      if: matrix.os == 'macos-latest'
      run: |
        brew install bash bats-core

    - name: Install bats (Ubuntu)
      if: matrix.os == 'ubuntu-latest'
      run: |
        apt-get install -y bats

    - name: Run tests
      run: |
        bats tests
